apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: disparador-cliente-api-kube
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: cliente-api-kube-binding
  template:
    name: cliente-api-kube-template
