apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-manifests
spec:
  workspaces:
  - name: source
  params:
    - name: manifest_dir
      description: El directorio que contiene los yaml para el despliegue
      type: string
      default: "k8s"
  steps:
    - name: apply
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Aplicado manifiestos del directorio $(inputs.params.manifest_dir)
          oc apply -f $(inputs.params.manifest_dir)
          echo -----------------------------------
