@ -1,30 +0,0 @@
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clienteapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: clienteapi
    spec:
      containers:
      - name: clienteapi
        image: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/clienteapi
        imagePullPolicy: Always
