apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clienteapi
  name: clienteapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clienteapi
  template:
    metadata:
      labels:
        app: clienteapi
    spec:
      containers:
      - name: clienteapi
        image: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/clienteapi
        ports:
          - containerPort: 3000
            protocol: TCP
