apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cliente-api-kube
  name:  cliente-api-kube-route
spec:
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: cliente-api-kube-service
    weight: 100
  wildcardPolicy: None
