apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: clienteapi
  name: clienteapi-route
spec:
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: clienteapi
    weight: 100
  wildcardPolicy: None
